name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > jwt-key.pem
          chmod 600 jwt-key.pem

      - name: Copy JAR to EC2
        run: |
          scp -o StrictHostKeyChecking=no -i jwt-key.pem out/artifacts/jwt_validator_api_jar/jwt-validator-api.jar ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/jwt-validator-api.jar

      - name: Restart application on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i jwt-key.pem ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            pkill -f 'java.*jwt-validator-api.jar' || true
            nohup java -jar /home/ubuntu/jwt-validator-api.jar > app.log 2>&1 &
          EOF
